#!/usr/bin/env ruby
Dir.glob("./*.gem").each { |path| `rm #{path}` }
puts `gem uninstall -x dotenv-s3`
puts `gem build dotenv-s3.gemspec`
Dir.glob("./*.gem").each { |path| puts `gem install -f #{path}` }
